### ISSUE TITLE
 On iOS, we should always auto consume

### ISSUE THREAD

**Issue by stonith404** [riturajshakti/SuperEasyInAppPurchase#1]
By buying a product on Ios:
`  await inAppPurchase.startPurchase( 'myId', isConsumable: true);`

I get the following error:

`_AssertionError ('package:in_app_purchase/src/in_app_purchase/app_store_connection.dart': Failed assertion: line 82 pos 12: 'autoConsume == true': On iOS, we should always auto consume)`

On android it works fine. Is that a bug or can I give the paramater "auto consume"?

**Comment by riturajshakti** [comment]
Thank for your valuable feedback,
I will fix that soon.

**Comment by stonith404** [comment]
Was this fixed by the latest update?

**Comment by riturajshakti** [comment]
Yes, I fixed that issue.

**Comment by stonith404** [comment]
Thank you @riturajshakti ! So I will close this issue.

**Comment by riturajshakti** [comment]
Thanks,
Happy coding
