### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by amigax** [riturajshakti/SuperEasyInAppPurchase#4]
How do we configure the android and ios side to make this work? I dont see any instructions.. can it support subscription too ?

**Comment by riturajshakti** [comment]
You have to create In app purchase product in your Google Play Store
Console and Apple App Store Console. Also this plugin doesn't support
subscriptions.

**Comment by amigax** [comment]
ahh ok, but im sure there are steps to manifest etc, and linking the products. Anyway thanks I need subscription so will use different lib.

**Comment by riturajshakti** [comment]
Ok Sure.
I am planing to add subscriptions. But I am currently busy in building my
own freelancing site. I'll add subscriptions once this project is completed

**Comment by FazliMolaJan** [comment]
I would love to see subscriptions as well in super easy way like this.
